//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NubiHR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NubiHR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRSystem.Resources.NubiHR", typeof(NubiHR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More Certificates.
        /// </summary>
        public static string AddMoreCertificates {
            get {
                return ResourceManager.GetString("AddMoreCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new employee.
        /// </summary>
        public static string AddNewEmployee {
            get {
                return ResourceManager.GetString("AddNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Employees.
        /// </summary>
        public static string AllEmployees {
            get {
                return ResourceManager.GetString("AllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackTolist {
            get {
                return ResourceManager.GetString("BackTolist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string BankBranch {
            get {
                return ResourceManager.GetString("BankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Information.
        /// </summary>
        public static string BankInfo {
            get {
                return ResourceManager.GetString("BankInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse a File.
        /// </summary>
        public static string BrowseFile {
            get {
                return ResourceManager.GetString("BrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Employee.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Details.
        /// </summary>
        public static string EmployeeDetails {
            get {
                return ResourceManager.GetString("EmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee has been modified succesfully.
        /// </summary>
        public static string EmployeeHasBeenAddedSuccesfully {
            get {
                return ResourceManager.GetString("EmployeeHasBeenAddedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been modified succesfully.
        /// </summary>
        public static string EmployeeHasBeenModifiedSuccesfully {
            get {
                return ResourceManager.GetString("EmployeeHasBeenModifiedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s Information.
        /// </summary>
        public static string EmployeeInfo {
            get {
                return ResourceManager.GetString("EmployeeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Number.
        /// </summary>
        public static string FunctionalNumber {
            get {
                return ResourceManager.GetString("FunctionalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR System.
        /// </summary>
        public static string HRSystem {
            get {
                return ResourceManager.GetString("HRSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Title.
        /// </summary>
        public static string ImageTitle {
            get {
                return ResourceManager.GetString("ImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Information.
        /// </summary>
        public static string JobInfo {
            get {
                return ResourceManager.GetString("JobInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Certificate.
        /// </summary>
        public static string LastCertificate {
            get {
                return ResourceManager.GetString("LastCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Certificate Title.
        /// </summary>
        public static string LastCertificateTitle {
            get {
                return ResourceManager.GetString("LastCertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Phone Number.
        /// </summary>
        public static string Mobile2 {
            get {
                return ResourceManager.GetString("Mobile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string NationalID {
            get {
                return ResourceManager.GetString("NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID Title.
        /// </summary>
        public static string NationalIDTitle {
            get {
                return ResourceManager.GetString("NationalIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Title.
        /// </summary>
        public static string PassportTitle {
            get {
                return ResourceManager.GetString("PassportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Information.
        /// </summary>
        public static string PhoneInfo {
            get {
                return ResourceManager.GetString("PhoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Certificate.
        /// </summary>
        public static string RemoveCertificate {
            get {
                return ResourceManager.GetString("RemoveCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Information.
        /// </summary>
        public static string SalaryInfo {
            get {
                return ResourceManager.GetString("SalaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select --.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Certificate.
        /// </summary>
        public static string TrainingCertificate {
            get {
                return ResourceManager.GetString("TrainingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Certificate Title.
        /// </summary>
        public static string TrainingCertificateTitle {
            get {
                return ResourceManager.GetString("TrainingCertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Number.
        /// </summary>
        public static string WorkNumber {
            get {
                return ResourceManager.GetString("WorkNumber", resourceCulture);
            }
        }
    }
}
