//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NubiHR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NubiHR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRSystem.Resources.NubiHR", typeof(NubiHR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add attachment.
        /// </summary>
        public static string AddAttachment {
            get {
                return ResourceManager.GetString("AddAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More Certificates.
        /// </summary>
        public static string AddMoreCertificates {
            get {
                return ResourceManager.GetString("AddMoreCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new employee.
        /// </summary>
        public static string AddNewEmployee {
            get {
                return ResourceManager.GetString("AddNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add siblings.
        /// </summary>
        public static string AddSiblings {
            get {
                return ResourceManager.GetString("AddSiblings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All attendance sheets.
        /// </summary>
        public static string AllAttendanceSheets {
            get {
                return ResourceManager.GetString("AllAttendanceSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Employees.
        /// </summary>
        public static string AllEmployees {
            get {
                return ResourceManager.GetString("AllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Emp.
        /// </summary>
        public static string AlternativeEmp {
            get {
                return ResourceManager.GetString("AlternativeEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You Want To Delete This?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThis {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Type.
        /// </summary>
        public static string AttachmentType {
            get {
                return ResourceManager.GetString("AttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance sheets.
        /// </summary>
        public static string AttendanceSheets {
            get {
                return ResourceManager.GetString("AttendanceSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackTolist {
            get {
                return ResourceManager.GetString("BackTolist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string BankBranch {
            get {
                return ResourceManager.GetString("BankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Information.
        /// </summary>
        public static string BankInfo {
            get {
                return ResourceManager.GetString("BankInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse a File.
        /// </summary>
        public static string BrowseFile {
            get {
                return ResourceManager.GetString("BrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Permission Request.
        /// </summary>
        public static string CreatePermissionRequest {
            get {
                return ResourceManager.GetString("CreatePermissionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is expired.
        /// </summary>
        public static string DateIsExpired {
            get {
                return ResourceManager.GetString("DateIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done filtering.
        /// </summary>
        public static string DoneFiltering {
            get {
                return ResourceManager.GetString("DoneFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Employee.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Permission Request.
        /// </summary>
        public static string EditPermissionRequest {
            get {
                return ResourceManager.GetString("EditPermissionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact.
        /// </summary>
        public static string EmergencyContact {
            get {
                return ResourceManager.GetString("EmergencyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Details.
        /// </summary>
        public static string EmployeeDetails {
            get {
                return ResourceManager.GetString("EmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee has been added succesfully.
        /// </summary>
        public static string EmployeeHasBeenAddedSuccesfully {
            get {
                return ResourceManager.GetString("EmployeeHasBeenAddedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been modified succesfully.
        /// </summary>
        public static string EmployeeHasBeenModifiedSuccesfully {
            get {
                return ResourceManager.GetString("EmployeeHasBeenModifiedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s Information.
        /// </summary>
        public static string EmployeeInfo {
            get {
                return ResourceManager.GetString("EmployeeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee requests.
        /// </summary>
        public static string EmployeeRequests {
            get {
                return ResourceManager.GetString("EmployeeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Friday and Saturday.
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is already a file with the same name! please change the upload file name!.
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Number.
        /// </summary>
        public static string FunctionalNumber {
            get {
                return ResourceManager.GetString("FunctionalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR System.
        /// </summary>
        public static string HRSystem {
            get {
                return ResourceManager.GetString("HRSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Title.
        /// </summary>
        public static string ImageTitle {
            get {
                return ResourceManager.GetString("ImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is expired?.
        /// </summary>
        public static string IsExpired {
            get {
                return ResourceManager.GetString("IsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Information.
        /// </summary>
        public static string JobInfo {
            get {
                return ResourceManager.GetString("JobInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Certificate.
        /// </summary>
        public static string LastCertificate {
            get {
                return ResourceManager.GetString("LastCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Certificate Title.
        /// </summary>
        public static string LastCertificateTitle {
            get {
                return ResourceManager.GetString("LastCertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader Requests.
        /// </summary>
        public static string LeaderRequests {
            get {
                return ResourceManager.GetString("LeaderRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.. .
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Report.
        /// </summary>
        public static string MedicalReport {
            get {
                return ResourceManager.GetString("MedicalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Phone Number.
        /// </summary>
        public static string Mobile2 {
            get {
                return ResourceManager.GetString("Mobile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start with 0 (Length must be 10 digits).
        /// </summary>
        public static string MobileValidation {
            get {
                return ResourceManager.GetString("MobileValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Address During Vacation.
        /// </summary>
        public static string MyAddressDuringVacation {
            get {
                return ResourceManager.GetString("MyAddressDuringVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string NationalID {
            get {
                return ResourceManager.GetString("NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID Title.
        /// </summary>
        public static string NationalIDTitle {
            get {
                return ResourceManager.GetString("NationalIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New permission request.
        /// </summary>
        public static string NewPermissionRequests {
            get {
                return ResourceManager.GetString("NewPermissionRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New requests.
        /// </summary>
        public static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New vacation request.
        /// </summary>
        public static string NewVacationRequest {
            get {
                return ResourceManager.GetString("NewVacationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Hours.
        /// </summary>
        public static string NoOfHours {
            get {
                return ResourceManager.GetString("NoOfHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of row.
        /// </summary>
        public static string NoOfRow {
            get {
                return ResourceManager.GetString("NoOfRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        public static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: &apos;Remove&apos; operation will remove the last thing you added.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nubi IT Service.
        /// </summary>
        public static string Nubi {
            get {
                return ResourceManager.GetString("Nubi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Title.
        /// </summary>
        public static string PassportTitle {
            get {
                return ResourceManager.GetString("PassportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Date.
        /// </summary>
        public static string PermissionDate {
            get {
                return ResourceManager.GetString("PermissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission requests.
        /// </summary>
        public static string PermissionRequests {
            get {
                return ResourceManager.GetString("PermissionRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Type.
        /// </summary>
        public static string PermissionType {
            get {
                return ResourceManager.GetString("PermissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Information.
        /// </summary>
        public static string PhoneInfo {
            get {
                return ResourceManager.GetString("PhoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Accept My Vacation Described Above For a Period Of.
        /// </summary>
        public static string PleaseAcceptMyVacationDescribedAboveForAPeriodOf {
            get {
                return ResourceManager.GetString("PleaseAcceptMyVacationDescribedAboveForAPeriodOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch Time.
        /// </summary>
        public static string PunchTime {
            get {
                return ResourceManager.GetString("PunchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type.
        /// </summary>
        public static string RelationshipType {
            get {
                return ResourceManager.GetString("RelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining hours.
        /// </summary>
        public static string RemainingHours {
            get {
                return ResourceManager.GetString("RemainingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Attachment.
        /// </summary>
        public static string RemoveAttachment {
            get {
                return ResourceManager.GetString("RemoveAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove attachment type.
        /// </summary>
        public static string RemoveAttachmentType {
            get {
                return ResourceManager.GetString("RemoveAttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Certificate.
        /// </summary>
        public static string RemoveCertificate {
            get {
                return ResourceManager.GetString("RemoveCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove siblings.
        /// </summary>
        public static string RemoveSiblings {
            get {
                return ResourceManager.GetString("RemoveSiblings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Date.
        /// </summary>
        public static string ResumeDate {
            get {
                return ResourceManager.GetString("ResumeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Information.
        /// </summary>
        public static string SalaryInfo {
            get {
                return ResourceManager.GetString("SalaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select --.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Employee.
        /// </summary>
        public static string SelectEmployee {
            get {
                return ResourceManager.GetString("SelectEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull.
        /// </summary>
        public static string Successfull {
            get {
                return ResourceManager.GetString("Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Alternative Employee Will Be.
        /// </summary>
        public static string TheAlternativeEmployeeWillBe {
            get {
                return ResourceManager.GetString("TheAlternativeEmployeeWillBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time From.
        /// </summary>
        public static string TimeFrom {
            get {
                return ResourceManager.GetString("TimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time To.
        /// </summary>
        public static string TimeTo {
            get {
                return ResourceManager.GetString("TimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Certificate.
        /// </summary>
        public static string TrainingCertificate {
            get {
                return ResourceManager.GetString("TrainingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Certificate Title.
        /// </summary>
        public static string TrainingCertificateTitle {
            get {
                return ResourceManager.GetString("TrainingCertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload an Excel file .
        /// </summary>
        public static string UploadAllowedExcelExtensions {
            get {
                return ResourceManager.GetString("UploadAllowedExcelExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload file having extensions .jpeg , .jpg , .png , .gif , .doc , .docx , .pdf only.
        /// </summary>
        public static string UploadAllowedExtensions {
            get {
                return ResourceManager.GetString("UploadAllowedExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload file having extensions .jpeg , .jpg , .png , .gif , .pdf only.
        /// </summary>
        public static string UploadAllowedMedicalExtensions {
            get {
                return ResourceManager.GetString("UploadAllowedMedicalExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation requests.
        /// </summary>
        public static string VacationRequests {
            get {
                return ResourceManager.GetString("VacationRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VacationType.
        /// </summary>
        public static string VacationType {
            get {
                return ResourceManager.GetString("VacationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Number.
        /// </summary>
        public static string WorkNumber {
            get {
                return ResourceManager.GetString("WorkNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkState.
        /// </summary>
        public static string WorkState {
            get {
                return ResourceManager.GetString("WorkState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong excel sheet.
        /// </summary>
        public static string WrongExcelSheet {
            get {
                return ResourceManager.GetString("WrongExcelSheet", resourceCulture);
            }
        }
    }
}
