//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int Id { get; set; }
        public string AlertText { get; set; }
        public string Link { get; set; }
        public Nullable<int> MsgSmsId { get; set; }
        public Nullable<int> MsgEmailId { get; set; }
        public string MsgSmsText { get; set; }
        public string MsgEmailText { get; set; }
        public bool IsSendSms { get; set; }
        public bool IsSendEmail { get; set; }
        public bool IsOpen { get; set; }
        public Nullable<System.DateTime> DateSendSms { get; set; }
        public Nullable<System.DateTime> DateSendEmail { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public bool IsHiddenInNavbar { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string UserId { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public string EmailSubject { get; set; }
        public string AttachmentPath { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
