//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceSheet
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public System.DateTime PunchTime { get; set; }
        public string WorkState { get; set; }
        public string Terminal { get; set; }
        public string PunchType { get; set; }
        public string NoOfHours { get; set; }
        public string RemainingHours { get; set; }
        public string ImportLogNo { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ImportLog ImportLog { get; set; }
    }
}
