//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyContact
    {
        public int Id { get; set; }
        public string EmpNo { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public int RelationshipTypeNo { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual RelationshipType RelationshipType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
