//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.PermissionRequests = new HashSet<PermissionRequest>();
            this.TrainingCertificates = new HashSet<TrainingCertificate>();
            this.VacationRequests = new HashSet<VacationRequest>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Email { get; set; }
        public int FunctionalNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public int DepartmentNo { get; set; }
        public int PositionNo { get; set; }
        public int AttachmentNo { get; set; }
        public Nullable<int> BankNo { get; set; }
        public int SalaryNo { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual Department Department { get; set; }
        public virtual Position Position { get; set; }
        public virtual Salary Salary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionRequest> PermissionRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingCertificate> TrainingCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacationRequest> VacationRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
