//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraSalary
    {
        public int Id { get; set; }
        public int SalaryNo { get; set; }
        public double ExtraHours { get; set; }
        public double Amount { get; set; }
        public long IsDeleted { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Salary Salary { get; set; }
    }
}
