//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public int Id { get; set; }
        public string Mobile { get; set; }
        public string Home { get; set; }
        public string WorkNumber { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Date { get; set; }
    }
}
