//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public int PermissionPerMonth { get; set; }
        public int VacationPerYear { get; set; }
        public System.DateTime Date { get; set; }
        public double VacationPerMonth { get; set; }
        public bool IsDeleted { get; set; }
    }
}
