//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public string SESSIONID { get; set; }
        public string UserID { get; set; }
        public string APPLICATIONNAME { get; set; }
        public System.DateTime CREATED { get; set; }
        public Nullable<System.DateTime> EXPIRES { get; set; }
        public Nullable<System.DateTime> LOCKDATE { get; set; }
        public Nullable<decimal> LOCKID { get; set; }
        public Nullable<decimal> TIMEOUT { get; set; }
        public Nullable<bool> LOCKED { get; set; }
        public string SESSIONITEMS { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public string IpAddress { get; set; }
        public string UserAgent { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string LastIndexUrl { get; set; }
        public Nullable<byte> CurrentRole { get; set; }
        public Nullable<long> CurrentRoleProviderId { get; set; }
        public Nullable<long> CurrentRoleJpcId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
